---
- name: Установка пакетов, создание виртуальной среды, загрузка кода, установка библиотек, обновление файла настроек и запуск приложения.
  hosts: localhost
  become: no
  vars_prompt:
    - name: secret_token
      prompt: Введите telegram-token
      private: false

  tasks:
    - name: Установка пакета python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Установка пакета python3-virtualenv
      apt:
        name: python3-virtualenv
        state: present

    - name: Установка пакета git
      apt:
        name: git
        state: present

    - name: Клонирование репозитория
      ansible.builtin.git:
        repo: 'https://github.com/KrivoSoft/Anna.git'
        dest: "{{ ansible_env.HOME }}/Anna"
        clone: yes

    - name: Создание виртуальной среды
      ansible.builtin.command:
        cmd: virtualenv env
      args:
        chdir: "{{ ansible_env.HOME }}/Anna"
      register: venv_output

    - name: Установка библиотек из requirements.txt
      ansible.builtin.pip:
        requirements: "{{ ansible_env.HOME }}/Anna/requirements.txt"
        virtualenv: "{{ ansible_env.HOME }}/Anna/env"
