---
- name: Установка пакетов, создание виртуальной среды, загрузка кода, установка библиотек, обновление файла настроек и запуск приложения.
  hosts: localhost
  become: no
  tasks:
    - name: Установка пакета python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Установка пакета python3-virtualenv
      apt:
        name: python3-virtualenv
        state: present

    - name: Создание виртуальной среды
      ansible.builtin.command:
        cmd: virtualenv env
      args:
        chdir: "{{ ansible_env.HOME }}/Anna"
      register: venv_output

    - name: Установка библиотек из requirements.txt
      ansible.builtin.pip:
        requirements: "{{ ansible_env.HOME }}/Anna/requirements.txt"
        virtualenv: Anna/env
