---
- name: Установка пакетов, создание виртуальной среды, загрузка кода, установка библиотек, обновление файла настроек и запуск приложения.
  hosts: localhost
  become: no
  vars_prompt:
    - name: secret_token
      prompt: Введите telegram-token
      private: false

    - name: parking_spots
      prompt: 'Введите названия парковочных мест. Пример: ["333", "464", "501"]'
      private: false

  tasks:
    - name: Установка пакета python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Установка пакета python3-virtualenv
      apt:
        name: python3-virtualenv
        state: present

    - name: Установка пакета git
      apt:
        name: git
        state: present

    - name: Клонирование репозитория
      ansible.builtin.git:
        repo: 'https://github.com/KrivoSoft/Anna.git'
        dest: "{{ ansible_env.HOME }}/Anna"
        clone: yes

    - name: Создание виртуальной среды
      ansible.builtin.command:
        cmd: virtualenv env
      args:
        chdir: "{{ ansible_env.HOME }}/Anna"

    - name: Установка библиотек из requirements.txt
      ansible.builtin.pip:
        requirements: "{{ ansible_env.HOME }}/Anna/requirements.txt"
        virtualenv: "{{ ansible_env.HOME }}/Anna/env"

    - name: Копирование конфигурационного файла
      ansible.builtin.copy:
        src: "{{ ansible_env.HOME }}/Anna/example_settings.yml"
        dest: "{{ ansible_env.HOME }}/Anna/settings.yml"

    - name: Замена токена в конфигурационном файле
      ansible.builtin.replace:
        path: "{{ ansible_env.HOME }}/Anna/settings.yml"
        regexp: 'YOUR_TOKEN'
        replace: "{{ secret_token }}"

    - name: Замена названий парковочных мест в конфигурационном файле
      ansible.builtin.replace:
        path: "{{ ansible_env.HOME }}/Anna/settings.yml"
        regexp: '\["333", "464", "501"\]'
        replace: "{{ parking_spots }}"

    - name: Запуск бота в виртуальном окружении
      ansible.builtin.command:
        cmd: "{{ ansible_env.HOME }}/Anna/env/bin/python3 {{ ansible_env.HOME }}/Anna/run.py &"
      register: run_output

    - name: Результат запуска
      ansible.builtin.debug:
        msg: "{{ run_output }}"